[[descriptions]]
= Description of selected parts of the transaction

The transaction is based upon the definitions of {name-transaction-org} described in {link-profile}. Business terms, Business rules and code lists used are inherited from the following {link-bii3} and {eforms-specs} and {regrep} documents:

== Parties

=== Economic operator

The economic operator is the party submitting the tender, and is any natural or legal person or public entity or group of such persons and/or entities, including any temporary association of undertakings, which offers the execution of works and/or a work, the supply of products or the provision of services on the market.


[source,xml,indent=0]
.Economic operator is represented in UBL 2.2 using the TendererParty
[source,xml,indent=0]
....
include::../files/NotifiyAwarding.xml[tags=SenderParty]
....

=== Contracting Body

The contracting body is the contracting authority or contracting entity who is buying supplies, services or tendering works.

[source,xml,indent=0]
.Example

----
include::../{xml-doc-file}[tags=ContractingParty]
----
<1> The only required element is the `cac:PartyIdentification/cbc:ID`, but it is recommended to inform the `cbc:EndpointID` and the `cbc:Name` as depicted in the example above.
