
= Document references

== Tender document reference

The tender reception notification contains the reference to the tender document sent by the economic operator. The contracting authority should refer to the tender by using the document hash and the hash algorithm method used.

DocumentReference Identifier for a Call for Tender Reference must be expressed in a UUID syntax (RFC 4122).

////
[source,xml,indent=0]
.DocumentHash

----
include::../{xml-doc-file}[tags=DocumentHash]
----
////
Document hash algorithm must be http://www.w3.org/2001/04/xmlenc#sha256[SHA-256].
////
[source,xml,indent=0]
.Document hash algorithm

----
include::../{xml-doc-file}[tags=HashAlgorithmMethod]
----

////

[source,xml,indent=0]
.Tender document reference

----
include::../{xml-doc-file}[tags=TenderDocumentReference]
----


== Document Type Code

The type of business document must also be included in the document reference element. Document Type
Code is coded according to code list 1001 issued by UN/CEFACT. For a complete list of all
the document types, see {un-ece-1001}.

[source,xml,indent=0]
.Document Type Code
----
include::../{xml-doc-file}[tags=DocumentTypeCode]
----
