
= Qualification documents

== Referenced lots

[source,xml,indent=0]
----
include::../files/Qualification-doc.xml[tags=InterestedProcurementProjectLot]
----

<.> UUID identifier to reference the lot for which the call for tender qualification is valid, lot number follows double colons


== Attached documents

The class cac:AdditionalDocumentReference is used to attach the tender documents or their references.

Example below shows the attached tender document and its hash and algorithm. The attached tender document is in this example unstructured.

[source,xml,indent=0]
----
include::../files/Qualification-doc.xml[tags=AdditionalDocumentReference]
----
<.> ID of the referenced call for tender document
<.> ID and lot ID of the tendering documents
<.> The type of business document must also be included in the document reference element. Document Type
Code is coded according to code list 1001 issued by UN/CEFACT. For a complete list of all
the document types, see https://service.unece.org/trade/untdid/d99a/uncl/uncl1001.htm[UNCL 1001]. In this message the following codes are used:
* 310 (Offer/quotation): Tender reference
* 311 (Request for quote): Call for tender reference
* 916 (Related document): ESPD response
<.> Code indicating the location of the tenderer
<.> Version of the reference call for tender, must be an integer
<.> Free textual description of the call for tender
<.> Beginning of the actual attachment
<.> URI identifying the attached document
<.> Hash proving the identity of the attachment
<.> Used hash algorithm, must be 'http://www.w3.org/2001/04/xmlenc#sha256</'
<.> Mime code of the attachment
<.> File name of the attachment
<.> Size of the attachment