
= Document References

The class cac:AdditionalDocumentReference is used to attach the qualification documents or other references such as the Call for Tender reference.

Example below shows an attached qualification document, its hash and algorithm. The attached qualification document is in this example unstructured. An additional reference to the Call for Tender is included.

[source,xml,indent=0]
----
include::../files/Qualification-doc.xml[tags=AdditionalDocumentReference]
----
<.> ID of the referenced qualification document
<.> The type of business document must also be included in the document reference element. In this case the code 916 is used to reference to a qualification document. Document Type
Code is coded according to code list 1001 issued by UN/CEFACT ( see https://service.unece.org/trade/untdid/d99a/uncl/uncl1001.htm[UNCL 1001]). In this message the following codes are allowed:
* 311 (Request for quote): Call for tender reference
* 916 (Related document): Qualification document (e.g. ESPD response)
<.> XPath reference to the party to whom this qualification document belongs
<.> Code indicating the language of the qualification document
<.> Version of the referenced qualification document, must be an integer
<.> Free textual description of the qualification document
<.> The actual document that is attached
<.> URI identifying the attached qualification document in the ASiC-E Container
<.> Hash value to prove the integrity of the attached qualification document
<.> Used hash algorithm, must be 'http://www.w3.org/2001/04/xmlenc#sha256</'
<.> Mime code of the attachment
<.> File name of the attachment
<.> Size of the attachment
<.> Another Document Reference pointing to the Call for Tender
<.> ID of the Call for Tenders document
<.> The type of business document must also be included in the document reference element. In this case the code 311 is used to reference to the Call for Tender. Document Type Code is coded according to code list 1001 issued by UN/CEFACT ( see https://service.unece.org/trade/untdid/d99a/uncl/uncl1001.htm[UNCL 1001]). In this message the following codes are allowed:
* 311 (Request for quote): Call for tender reference
* 916 (Related document): Qualification document (e.g. ESPD response)