
= Key examples

== Prior Information Notice

*Example 1*

An economic operator finds an interesting business opportunity after a search on a platform with published notices. He knows how to respond to the opportunity because he can find all the relevant information in the Contract notice. He receives the Call for tenders with all supporting documents. The documents are unstructured and attached as files to the call for tender. The economic operator prepares his qualification information. He creates a ESPD based on the template provided by the contracting body. The ESPD is a regular PDF document and attached to his qualification. In a restricted procedure the economic operator request to participate by using the qualification profile.

*Example 2*

A contracting body used a prequalification system to shortlist economic operators. To get on this list economic operators answers the qualification criteria, gathers all evidence needed and use the qualification profile to send all this information to the contracting body. The contracting body receives the qualification information and assesses if the economic operator will be added on the list.