
= Document references

== Tender document reference

The qualification reception notification contains the reference to the qualification document sent by the economic operator. The contracting authority should refer to the tender by using the document hash and the hash algorithm method used.

DocumentReference Identifier for a Call for Tender Reference must be expressed in a UUID syntax (RFC 4122).

[source,xml,indent=0]
.DocumentHash

----
include::../files/QualificationResponse-doc.xml[tags=DocumentHash]
----

Document hash algorithm must be http://www.w3.org/2001/04/xmlenc#sha256[SHA-256].

[source,xml,indent=0]
.Document hash algorithm

----
include::../files/QualificationResponse-doc.xml[tags=HashAlgorithmMethod]
----

[source,xml,indent=0]
.Tender document reference

----
include::../files/QualificationResponse-doc.xml[tags=TenderDocumentReference]
----
<.> DocumentTypeCode 13 for the receipt of the Qualification documents


== Document Type Code

The type of business document must also be included in the document reference element. Document Type
Code is coded according to code list 1001 issued by UN/CEFACT. For a complete list of all
the document types, see https://service.unece.org/trade/untdid/d99a/uncl/uncl1001.htm[UNCL 1001]. The code used to reference the REM-Evidence regarding the time of arrival of
a tender is 13 (Post receipt)

[source,xml,indent=0]
.Document Type Code
----
include::../files/QualificationResponse-doc.xml[tags=DocumentTypeCode]
----

=== Issuer Party

Party, which issued the reception, not always the final receiving party of the message.

[source,xml,indent=0]
....
include::../files/QualificationResponse-doc.xml[tags=IssuerParty]
....
