=	Description of the attachment of documents

Using this transaction, the information of the tendering process and the details of the procurement project are described in unstructured files. The call for tenders reference the unstructured files so it is possible to access them through their URI.

The `cac:AdditionalDocumentReference` class contains references to all the files for the tenderers to prepare their bids. The mandatory `cbc:ID` element contains an identifier of the file, and the `cac:DocumentStatusCode` is used to inform the tenderer about the action that has to be done with the current document.

Find below an example on how to define a provided document reference based on the e-SENS pilot project.

In this example, the contents of the coded elements DocumentTypeCode and DocumentStatusCode have been defined following the e-SENS project coded values.


[source,xml,indent=0]
.Additional document reference

----
include::../{xml-doc-fil}[tags=AdditionalDocumentReference2]

----
