
== Tendering Message Response Principles

The Tendering Message Response is intended to inform the issuer of the following situations

1. The received notice transaction or the notice payload contained errors according to the relevant conformance rules.
* The notice will not be processed any further.

2. The received notice transaction and the notice payload passed the validation of conformance rules without any fatal errors.
* The notice will be processed further.

 3. The received notice transaction or the notice payload are not validated for conformance but the receiver acknowledges that it has been received and identified as a business message.
* The notice will be processed further.

== The following errors are within the scope for a Tendering Message Response:

* Standard confirmation of acceptance for a well-formed message
* XML schema validation error
* Standard Compliance violations (e.g. empty elements not being allowed by UBL)
* Validation error of type fatal error
* Validation error of type warning. Warnings alone must NOT cause rejection of the business document (but they may be reported in addition to fatal errors)
* Wrong version of business document (will be handled like validation error of type fatal error)
* Unknown sender
* Unknown receiver
* Wrong version of envelope
* XML schema validation error – envelope
* XML not well-formed
* Non supported encoding

== The following concepts are outside the scope for a Tendering Message Response:

* Bi-directional communication – discussion on response.
* Enquiry of the Tendering Message Response.
* Transmission level status.
* Support for attachments.





