
= Code lists

The piloting of {link-esens} for Call for Tenders, is based on work done by {link-cenbii}[CEN BII], and business rules and code lists used are inherited from the following {link-cenbii}[CEN BII] documents:

* CWA 17027-212 UBL SIG - Trdm083 Call for Tenders
* CWA 17027-112 Profile 47 - Call for Tenders

In addition to the rules and code lists from the CEN BII work, the e-SENS pilot is using openPEPPOL Transport infrastructure, and some additional business rules has been added, to ensure correct use according to openPEPPOLPolicies. The testing/piloting has also revealed that there where a few other rules/code lists needed as validation artefacts to ensure an instance document is conformant with the CEN BII specifications.

The following chapters gives an overview of any code lists and business rules added by the e-SENS pilot project. For rules and code lists from CEN BII, we refer to the published documents above.



:leveloffset: +1

= Code lists

The following code lists for coded elements and identifier schemes are used in this e-SENS BIS.

NOTE: Additional code lists are listed in the CEN BII documents, and must also be used to ensure valid instance documents!


include::code-list-element.adoc[]
include::code-list-identifers-scheme.adoc[]
include::peppol.adoc[]


:leveloffset: -1
