[[descriptions]]
= Description of selected parts of the transaction

Limited support for this, see

{name-profile-org}.

== Submit Objects Request

* id indicates the id of the transmission in the form of an UUID
* mode has to be "_CreateOrVersion_" as it should be possible to both transfer a new submission or an updated version

[source,xml,indent=0]
.Example of usage of submit objects request basis
....
include::../files/ExamplePublishNotice.xml[tags=submit-objects-request;!specification-identification;!business-process-type-identifier;!issue-date-time;!sender-electronic-address;!receiver-electronic-address;!publication-requested;!registry-object-list]
....

== Issue Date and time

Issue date/time, and the registered date/time must be sent.

Issue date and received date are both xs:date data type, and the date is specified as "YYYY-MM-DD" where:

* YYYY - four digit year
* MM - two digit month (01 to 12)
* DD - two digit day (0)

Issue time and received time are both xs:time data type, and the time is specified as "hh:mm:ss" where:

* hh - two digits of hour (00 to 23) (am/pm NOT allowed).
* mm - two digits of minute (00 to 59)
* ss - two digits of second (00 to 59)
* TZD - time zone designator (Z or +hh:mm or -hh:mm)

The issue date and time refer to the actual issuance of the notice.

NOTE: The issue date, and the preferred publication date must specify the time zone.

[source,xml,indent=0]
.Example of Issue date and time
....
include::../files/ExamplePublishNotice.xml[tags=issue-date-time]
....
<.> Slot for date and time of issuing of the published notice
<.> SlotValue type has to be DateTimeValue
<.> Value tag were the issue date time has to be put, including the time zone

== Publication Request Indicator

This indicator shows if the attached notice needs to be published or if it only needs to be validated by the publication body. The check by the publication body can help the contracting party to determine the validity of the notice with regard to a possible publication.

[source,xml,indent=0]
.Example of usage of publication request indicator
....
include::../files/ExamplePublishNotice.xml[tags=publication-requested]
....
<.> Slot for the indication of the publication of the attached notices
<.> SlotValue type has to be BooleanValueType


== Registry Object (List)

This list contains all the notices, which will be published at once during this transaction. Each notice is represented as one registry object. The Registry Object contains the RepositoryItemRef, which is the reference to the notice itself.

[source,xml,indent=0]
.Example of usage of the registry object list (abbreviated)
....
include::../files/ExamplePublishNotice.xml[tags=registry-object-list;!information-about-buyer;!document-type-code;!notice-version;!additional-document-reference;!eforms-version]
....

<.> Beginning of the registry object list
<.> Each registry object is an Extrinsic Object Type. The Objects are identified by the lid (logical id) referencing the notice id and the id referencing the id of the publish notice
<.> At last in each registry object goes the reference to the notice as an eforms document.

== Notice Metadata

=== UBL Document Schema

Used to identify the UBL document schema of the referenced notice which are associated to the corresponding UBL namespaces. Use code according to code list document type issued by PEPPOL. For a complete list of all
the document types, see tbd.

[source,xml,indent=0]
.Example of usage of ubl document schema
....
include::../files/ExamplePublishNotice.xml[tags=document-type-code]
....
<.> The code "_CN_" for status information has to be put into the value tag. The listID as the SlotType is always "_http://docs.peppol.eu/document-type-code_" (tbd).

=== Notice Version

Version of the notice which shall be published. If this is not the first iteration of the notice choose a higher number than one, ideally counting up from the last version which was published.

[source,xml,indent=0]
.Example of usage of notice version
....
include::../files/ExamplePublishNotice.xml[tags=notice-version]
....
<.> Slot for the notice version
<.> SlotValue type has to be IntegerValueType, in this case 1.0 as it is the first version of the notice

=== eForms Version

Version of the used eForms specification for the notice. The format is according to the specification always eforms-x.y.

• “eforms-”: fixed prefix,
• “x”: major version number (increased everytime backward compatibility is affected),
• “y”: minor version number


[source,xml,indent=0]
.Example of usage of eForms version
....
include::../files/ExamplePublishNotice.xml[tags=eforms-version]
....
<.> Slot for the eForms version
<.> SlotValue type has to be StringValueType, as the format for the version will be always eforms-x.y


=== Buyer Party Identification

The information about the buyer includes different types of identification elements to disclose a way to contact the buyer without immediately opening the attached published notice. The buyer information are optional in the transaction.

The buyer party identification is an additional identifier for the buying organization. For optional use in the transaction.

[source,xml,indent=0]
.Example of usage of buyer party identification
....
include::../files/ExamplePublishNotice.xml[tags=buyer-party-identification]
....
<.> Slot for the buyer party identification, the type is always "_https://docs.peppol.eu/poacc/billing/3.0/codelist/ICD/_"
<.> SlotValue type has to be CollectionValueType and type of each element has to be StringValueType

=== Additional Document Reference

The Additional Document Reference specifies a reference to an additional file that is included to the local ASiC-E container (Associated Signature Container Extended) repository. For optional use.

The notice stored in a eForms based format must contain all the information of the notice, regardless of the place of publication. Therefore, the attached additional file shall contain only additional information to the notice (like statistical data) that is not part of the notice itself.

[source,xml,indent=0]
.Example of usage of additional document references
....
include::../files/ExamplePublishNotice.xml[tags=additional-document-reference]
....

<.> Example for an attachment, the type is used for the classification of the attachment
<.> Path to the file
<.> If needed additional attachments can be included in the same way as an additional slot


