[[descriptions]]
= Description of selected parts of the transaction

Limited support for this, see

{name-profile-org}.

== Process control

=== Specification Identification

Specifies the unique identifier for an the Request to publish a notice.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=specification-identification]
....
<.> The value for the specification identification is always "_urn:fdc:peppol.eu:prac:trns:t015:1.0_".


=== Business Process Type Identifier

Identifier for the business process context of the Publish Notice.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=business-process-type-identifier]
....
<.> The value for the business process type identifier is always "_urn:fdc:peppol.eu:prac:bis:p008:1.0_".

=== Sender Party

The party sending the notice.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=sender-electronic-address]
....
<.> Slot for the sender electronic address, including the schemeID in the type
<.> SlotValue type has to be StringValueType
<.> Value tag were the EndpointID has to be put

=== Receiver Party

The party receiving of the notice.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=receiver-electronic-address]
....
<.> Slot for the sender electronic address, including the schemeID in the type
<.> SlotValue type has to be StringValueType
<.> Value tag were the EndpointID has to be put


== Registry Object (List)

This list contains all the notices, which will be published at once during this transaction. Each notice is represented as one registry object. The Registry Object contains the RepositoryItemRef, which is the reference to the notice itself.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=registry-object-list;!information-about-buyer;!document-type-code;!notice-version]
....

<.> Beginning of the registry object list
<.> Each registry object is an Extrinsic Object Type. The Objects are identified by the lid (logical id) referencing the notice id and the id referencing the id of the publish notice
<.> At last in each registry object goes the reference to the notice as an eforms document.

=== UBL Document Schema

Used to identify the UBL document schema of the referenced notice which are associated to the corresponding UBL namespaces. Use code according to code list document type issued by PEPPOL. For a complete list of all
the document types, see tbd.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=document-type-code]
....
<.> The code "_CN_" for status information has to be put into the value tag. The listID as the SlotType is always "_http://docs.peppol.eu/document-type-code_" (tbd).

=== Notice Version

Version of the notice which shall be published. If this is not the first iteration of the notice choose a higher number than one, ideally counting up from the last version which was published.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=notice-version]
....
<.> Slot for the notice version
<.> SlotValue type has to be IntegerValueType, in this case 1.0 as it is the first version of the notice

=== Buyer Information

The information about the buyer includes different types of identification elements to disclose a way to contact the buyer without immediately opening the attached published notice. The buyer information are optional in the transaction.

==== Buyer Party Identification

The buyer party identification is an additional identifier for the buying organization. For optional use in the transaction.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=buyer-party-identification]
....
<.> Slot for the buyer party identification, the type is always "_https://docs.peppol.eu/poacc/billing/3.0/codelist/ICD/_"
<.> SlotValue type has to be CollectionValueType and type of each element has to be StringValueType

==== BuyerElectronicAddress
Identifies the buyer party's electronic address according to Electronic Address Scheme (EAS).

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=buyer-electronic-address]
....
<.> Slot for the sender electronic address, including the schemeID in the type
<.> SlotValue type has to be StringValueType
<.> Value tag were the EndpointID has to be put

=== Additional Document Reference

The Additional Document Reference specifies a reference to an additional file that is included to the local ASiC-E container (Associated Signature Container Extended) repository. For optional use.

[source,xml,indent=0]
....
include::../files/ExamplePublishNotice.xml[tags=additional-document-reference]
....

<.> Example for an attachment, the type is used for the classification of the attachment
<.> Path to the file
<.> If needed additional attachments can be included in the same way as an additional slot

== Date and time

Issue date/time, and the registered date/time must be sent.

Issue date and received date are both xs:date data type, and the date is specified as "YYYY-MM-DD" where:

* YYYY - four digit year
* MM - two digit month (01 to 12)
* DD - two digit day (0)

Issue time and received time are both xs:time data type, and the time is specified as "hh:mm:ss" where:

* hh - two digits of hour (00 to 23) (am/pm NOT allowed).
* mm - two digits of minute (00 to 59)
* ss - two digits of second (00 to 59)
* TZD - time zone designator (Z or +hh:mm or -hh:mm)

The issue date and time refer to the actual issuance of the notice.

NOTE: The issue date, and the preferred publication date must specify the time zone.

[source,xml,indent=0]
.Example of Issue date/time, the preferred publication date/time and the procurement documents change date/time
....
include::../files/ExamplePublishNotice.xml[tags=issue-date-time]
....
<.> Slot for date and time of issuing of the published notice
<.> SlotValue type has to be DateTimeValue
<.> Value tag were the issue date time has to be put, including the time zone
