[[descriptions]]
= Description of selected parts of the transaction

Limited support for this, see {name-profile-org}.

== Document References

=== Tender document reference

The tender reception notification contains the reference to the tender document sent by the economic operator. The contracting authority should refer to the tender by using the document hash and the hash algorithm method used.

DocumentReference Identifier for a Call for Tender Reference must be expressed in a UUID syntax (RFC 4122).

////
[source,xml,indent=0]
.DocumentHash

----
include::../{xml-doc-file}[tags=DocumentHash]
----
////
Document hash algorithm must be http://www.w3.org/2001/04/xmlenc#sha256[SHA-256].
////
[source,xml,indent=0]
.Document hash algorithm

----
include::../{xml-doc-file}[tags=HashAlgorithmMethod]
----

////

[source,xml,indent=0]
.Tender document reference

----
include::../files/TenderWithdrawalReceptionNotification.xml[tags=received-document-reference]
----


=== Document Type Code

The type of business document must also be included in the document reference element. Document Type
Code is coded according to code list 1001 issued by UN/CEFACT. For a complete list of all
the document types, see {link-un-ece-1001}.

[source,xml,indent=0]
.Document Type Code
----
include::../files/TenderWithdrawalReceptionNotification.xml[lines=38]
----
<.> The code "_23_" for status information has to be put into the tag. The listID has to be UNCL1001.

== Parties

=== Economic operator

The economic operator is the party submitting the tender and the recipient of the tender withdrawal reception notification, and is any natural or legal person or public entity or group of such persons and/or entities, including any temporary association of undertakings, which offers the execution of works and/or a work, the supply of products, or the provision of services on the market.

[source,xml,indent=0]
.Economic operator is represented in UBL 2.3 using ReceiverParty

[source,xml,indent=0]
....
include::../files/TenderWithdrawalReceptionNotification.xml[tags=economic-operator]
....
<.> As stated above, in UBL the Economic Operator is represented by the Receiver Party.
<.> At first the EndpointID with its schemeID has to be clarified. The schemeID is an attribute of the EndpointID and has to be chosen according to the EndpointID.
<.> Following the EndpointID the Identification of the Party has to be given in the same manner.
<.> The same value as in the EndpointID also the EndpointID has to be given into the ID and the corresponding attribute for the schemeID.
<.> At last the Name of the Economic Operator has to filled into the Name tag of the tag PartyName.

=== Contracting Body

The contracting body is the contracting authority or contracting entity who is buying supplies, services or tendering works.

[source,xml,indent=0]
.The contracting body is represented in UBL 2.3 using the SenderParty:

----
include::../files/TenderWithdrawalReceptionNotification.xml[tags=contracting-body]
----
<.> As stated above, in UBL the Contracting Body is represented by the Sender Party.
<.> At first the EndpointID with its schemeID has to be clarified. The schemeID is an attribute of the EndpointID and has to be chosen according to the EndpointID.
<.> Following the EndpointID the Identification of the Party has to be given in the same manner.
<.> The same value as in the EndpointID also the EndpointID has to be given into the ID and the corresponding attribute for the schemeID.
<.> At last the Name of the Economic Operator has to filled into the Name tag of the tag PartyName.

== Date and time

Issue date/time, and the registered date/time must be sent.

Issue date and received date are both xs:date data type, and the date is specified as "YYYY-MM-DD" where:

* YYYY - four digit year
* MM - two digit month (01 to 12)
* DD - two digit day (0)

Issue time and received time are both xs:time data type, and the time is specified as "hh:mm:ss" where:

* hh - two digits of hour (00 to 23) (am/pm NOT allowed).
* mm - two digits of minute (00 to 59)
* ss - two digits of second (00 to 59)
* TZD - time zone designator (Z or +hh:mm or -hh:mm)

The registered date and time are the times when the tender was actually received and its delivery was registered while the issue date and time refer to the issuance of the tender receipt notification.

NOTE: The issue time and registered time must specify the time zone.

[source,xml,indent=0]
.Example of Issue date/time and Registered date/time

----
include::../files/TenderWithdrawalReceptionNotification.xml[tags=document-issue-time-date]

include::../files/TenderWithdrawalReceptionNotification.xml[tags=document-reception-time-date]
----
