= Tendering procedures

Individual pre-award processes can be put in place using different procedures, depending on the value and the type of the contract to be awarded, on the legal nature of the contracting body and on specific member state national legislation {link-eu-directive}[(Directive 2014/24/EU art. 26)]. In open procedures, any economic operator can access the tender documents (including the call for tenders) and submit a tender before the time expires, without subscribing for interest and without any previous assessment of their capabilities. In restricted and negotiated procedures and in a competitive dialogue the interested economic operators must submit a request to participate in order to be invited in the tendering process by the contracting body. When the contracting body has published a notice, the interested economic operators may subscribe to obtain tendering information using profile BII60. Negotiated procedures require sending the invitation to tender (profile BII52) to identified candidates.

{link-eu-directive}[Article 26 to 32 from Directive 2014/24/EU] and {link-art43-50}[article 43 to 50 from Directive 2014/25/EU] describe the different tendering procedures that can be used by contracting bodies. For the purpose of electronic tendering, some of these procedures have been described in BII profiles BII37 (open procedure) and BII39 (restricted procedure). These profiles are included in CWA 17027-106 and CWA 17027-108.

Official notification through publishing bodies is part of many procedures. eNotification covers the electronic  transfer of electronic notices for publication and dissemination services with the ultimate aim of opening market opportunities. Profiles BII14 Prior Information Notice, BII10 Contract Notice and BII43 Contract Award Notice describe the exchange of a notice between a contracting body or his representative and a publisher.  Profile BII61 describes the exchange of notices between publishers. The process by which notices can be searched for on a given platform are described in profiles BII62 Exchange of Notice Metadata and BII45 Search Notices. These profiles are included in CWA 17026.
