= Changelog for March release 2023

== Profiles P001 - P011

*Release date 2023-xx-xx*

=== P012 - New Profile - Qualification Rejection 1.0


=== Business Rules

PEPPOL-T004-R038 was added to express that A Call For Tender T004 is only allowed to use une of the following ContractSystemCodes: 'Public Contract', 'Establishment of a Framework agreement' or 'Setting up a Dynamic Purchasing System'. Other ContractSystemCodes will be executed using Restricted Procedures and

  <rule context="ubl:CallForTenders/cac:TenderingProcess/cbc:ContractingSystemCode">
            <report id="PEPPOL-T004-S397" flag="warning" test="./@*[not(name()='listID')]"><value-of select="$syntaxError"/>[PEPPOL-T004-S397] ContractingSystemCode SHOULD NOT have any attributes but listID.</report>
            <assert id="PEPPOL-T004-R038" flag="fatal" test="not (cbc:ContractingSystemCode in ('1', '2', '3')">[PEPPOL-T004-R038] A Call For Tender is only allowed to use une of the following ContractSystemCodes: 'Public Contract', 'Establishment of a Framework agreement' or 'Setting up a Dynamic Purchasing System'.</assert>
        </rule>


=== Editorial changes



* Update context of PEPPOL Business Rule PEPPOL-T015-R022 (Schematron Rule Context was correct but assignement in Syntax mapping was not correct)

* Updated XML example for NUTS codes and CPV codes (Main /Additional commodity classification) in T004 and provided reference to the corresponding codelists of the publication office


