[[use-case-3-negative-response-violation-of-syntax-and-business-rules]]
= Use Case 3 – Negative response – violation of syntax and business rules

This use case is a message level response containing warnings due to violation business rules.

[cols="2s,6",options="header"]
|====
|Use Case number
|3

|Use Case Name
|Negative response – violation of business rules warnings

|Use Case Description
|This use case is a TMR based on a business document containing warnings due to violation of non-fatal business rules.

|Parties involved
|BusinessDocumentSender, MLRReceiver +
BusinessDocumentReceiver, MLRSender

|Status Code
|CA

|Possible Status Reason Codes
|BW, DL

|Assumptions
a|
.  The BusinessDocumentReceiver has received an electronic business document from the BusinessDocumentSender.
.  The BusinessDocumentReceiver has validated the business document from the BusinessDocumentSender.
.  The result of the validation is not OK due to violation of non-fatal business rules.

|The flow
a|
.  The BusinessDocumentSender has prepared and sent an electronic business document to the BusinessDocumentReceiver.
.  The BusinessDocumentReceiver has received the business document.
.  The BusinessDocumentReceiver has validated and found possible errors the business document.
.  The MLRSender has sent a TMR back to the MLRReceiver.
.  The MLRReceiver has received and processed the TMR and performed appropriate action to anticipate any future rejection of a similar incident.

|Result
a|
.  The TMR helped the BusinessDocumentSender to confirm that the business document was received and could be rejected by the BusinessDocumentReceiver.
. The BusinessDocumentSender may take appropriate action to correct and resend the business document.

|XML example file
|See Appendix A for a sample file illustrating Use Case 3.
|====
