[[use-case-2-negative-response-violation-of-business-rules]]
= Use Case 2 – Negative response – violation of business rules

This use case is a message level response which can be used to terminate a search request to not receive further results.

[cols="2s,6",options="header"]
|====
|Use Case number
|4

|Use Case Name
|Process termination

|Use Case Description
|This use case is a message level response based on a search notice, whose results are no longer requested.

|Parties involved
|SearchNoticeSender, MLRSender +
SearchNoticeReceiver, MLRReceiver

|Status Code
|RE

|Possible Status Reason Codes
|PT

|Assumptions
a|
.  The SearchNoticeReceiver has received an electronic search notice from the SearchNoticeSender.
.  The SearchNoticeReceiver has validated the search notice from the SearchNoticeSender.
.  The SearchNoticeReceiver has sent results matching the search from the SearchNoticeSender.
.  The SearchNoticeSender received sufficient results from the SearchNoticeReceiver.

|The flow
a|
.  The SearchNoticeSender has prepared and sent an electronic search notice to the SearchNoticeReceiver.
.  The SearchNoticeReceiver has received the search notice.
.  The SearchNoticeReceiver has validated the search notice.
.  The SearchNoticeReceiver sent page wise search results to the SearchNoticeSender.
.  The MLRSender has sent a message level response message back to the SearchNoticeReceiver.
.  The MLRReceiver has received and processed the message level response message and performed appropriate action due to the process termination.

|Result
a|
.  The message level response message helped the SearchNoticeSender to confirm that the search was concluded and it does not need more results.
The SearchNoticeReceiver must take appropriate action to stop the sending of search results.

|XML example file
|See Appendix A for a sample file illustrating Use Case 4.
|====
