
= Interoperability

This {peppol} BIS structure is based on the link:https://ec.europa.eu/isa2/home_en[European Interoperability Framework 2.0].

It applies the Framework as follows:

. Legal Interoperability
* Legal:
** {link-eu-directive}[Directive 2014/24/EU]
** link:http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014L0025&from=EN[Directive 2014/25/EU]
** link:http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014R0910&from=EN[Regulation 910/2014]

. Organizational interoperability
* Organization (Organization/Business):
** This {peppol} eTendering BIS supports only B2G
** This {peppol} eTendering BIS supports cross border, regional and domestic tendering procedures in EU and EEA
** This {peppol} eTendering BIS can function as a standardized EDI agreement within a trading community
** This {peppol} eTendering BIS supports linking of business processes within the sending and receiving organization.
** Organization (Process):
*** This {peppol} eTendering BIS supports a set of “common business processes” that are assumed to be supported by most enterprises whether public or private. These are processes that are used widely or understood as being relevant for most companies.

. Technical interoperability
* Technical Interaction (Process and semantic implementation):
** Binding to {link-e-SENS-SBDH}[e-SENS-SBDH]
** {link-e-SENS-SBDH}[ASiC-E container with CAdES signature]
** link:https://github.com/espd[ESPD Github Account]
////
. Semantic interoperability
* Semantic:
** A minimum set of information elements required to conduct a procurement procedure. The set of information elements is assumed to be sufficient to support organizational business and processing requirements stated above.
*** A CORE:
**** Data model, a set of elements that the receiver MUST be able to process.
**** Business rules, a set of business rules that ensure a common way of processing the information elements. The rules are stated in a way that allows for automated validation of document instances.
////
