// TODO

[[descriptions]]
= Description of selected parts of the transaction

The transaction including business terms, business rules and code lists are based upon the definitions of {name-transaction-org} described in:

{name-profile-org}.

== Identifier

=== UBL Version Identifier

Requires UBL version 2.2.

[source,xml,indent=0]
.Example of UBL Version Identifier
....
include::../files/QualificationRejection.xml[tags=UBL]
....
<.> Has to be 2.2, to correspondent to the used UBL version

=== Response Identifier

The identifier enables positive referencing the transaction instance for various purposes including referencing between transactions that are part of the same process. Must be expressed as a UUID.

[source,xml,indent=0]
.Example of response identifier
....
include::../files/QualificationRejection.xml[tags=ID]
....
<.> A transaction instance must contain an identifier, being expressed in uuid syntax

== Response issue date and time

Response issue date/time must be sent.

Response issue date is a xsi:date data type and is specified as "YYYY-MM-DD" where:

* YYYY - four digit year
* MM - two digit month (01 to 12)
* DD - two digit day (0)

Response issue time is a xsi:time data type and is specified as "hh:mm:ss" where:

* hh - two digits of hour (00 to 23) (am/pm NOT allowed).
* mm - two digits of minute (00 to 59)
* ss - two digits of second (00 to 59)
* TZD - time zone designator (Z or +hh:mm or -hh:mm)

The response issue date and time refer to the date when of the issuance of the response.

NOTE: The response issue time must specify the time zone.

[source,xml,indent=0]
.Example of response issue date and time
....
include::../files/QualificationRejection.xml[tags=IssueDateTime]
....
<.> Format for the date has to be yyyy-mm-dd
<.> Format for the time has to be hh:mm:ssTZD, granularity down to seconds and timezone

== Party identification

=== Sender Party

The party sending a Qualification Rejection Response message back to the party that initiated the request to qualify for a Procurement.

[source,xml,indent=0]
.Example of sender party
....
include::../files/QualificationRejection.xml[tags=SenderParty]
....
<.> Identifies the sender party's electronic address and the scheme identifier for the electronic address
<.> Identifies the sender party itself and the scheme identifier to resolve sender party's identifier

=== Receiver Party

The party who is supposed to process the Qualification Rejection Response. This is the same party that initiated the request to qualify for a Procurement.

[source,xml,indent=0]
.Example of receiver party
....
include::../files/QualificationRejection.xml[tags=ReceiverParty]
....
<.> Identifies the receiver party's electronic address and the scheme identifier for the electronic address
<.> Identifies the receiver party and the scheme identifier to resolve the receiver party's identifier

== QualificationResolution

The QualificationResolution returned with this transaction will always be negative. If more that one Lots have been aimed to qualify for and need to be rejected, one QualificationResolution has to estblished for each Lot.

[source,xml,indent=0]
.Example of QualificationResolution
....
include::../files/QualificationRejection.xml[tags=QualificationResolution]
....
<.> states that the Tenderer is not allowed to attend the further Procurement Process, only "false" is the allowed value here.
<.> If the QualificationRejection results from ExclusionGrounds, the corresponding values from the underlying codelist shall be taken.
<.> Otherwise one or more functional Reasons need to be textually given.
<.> The Date at which QualificationResolution has been passed
<.> The ProcurementProjectLot referenced in this QualificationRejection
<.> The ProcurementProjectLot's ID
<.> The Name of the ProcurementProjectLot as more reliable reference to a human reader - needed?


<!-- Still needed or need to be deleted? -->

== Document response

The notice response is used to indicate the result of business document validation. The element 'cac:DocumentResponse/cac:Response/cbc:ResponseCode' MUST contain the overall result code.

=== Response

A "rejection" (RE) states that the notice was not processed because of identified issues. "Conditionally accepted" (CA) indicates that the publication of the notice is done with warnings indicated in the message. "Accepted" (AP) indicates that the notice will be published at a certain time.

[source,xml,indent=0]
.Example of response
....
include::../files/QualificationRejection.xml[tags=response]
....
<.> An indicator stating whether the referenced message was cleared through validation and advanced to the next step in the process. Refer to codelist notice response.
<.> Used to make any comments or instructions relevant to the response. The use of this element requires manual assessment by the receiver.

=== Document reference

The document reference is used to provide references to notice request transaction and the notice payload. Thus, the transaction uses two levels of validation. The first one is the notice transaction itself, referenced with the `cbc:ID tag`. The second level is the notice which is included as payload and referenced with the `cbc:UUID`.

[source,xml,indent=0]
.Example of document reference
....
include::../files/QualificationRejection.xml[tags=documentReference]
....
<.> Specifies the unique identifier of the container that describes the request to publish a notice on which the Notice Publication Response is based, expressed in uuid syntax.
<.> An identification of the version of the underlying message.

=== Line response

A response to a particular line in the notice transaction or notice payload. If the document response is negative (code='RE'), the line response element is used to specify the errors in the notice.

The line response contains the line reference and the line response information

==== Line reference

Identifies the line in the notice transaction or notice payload to which the reported issue applies.

The LineID element must be used to indicate where in the notice the error occurred by using XPath to reference the element causing the error. To cater for scenarios where it is not possible to provide XPath, a dummy value must be applied. The dummy value must consist of the characters NA. This is due to that the LineID element is mandatory in the ApplicationResponse message in UBL 2.1 on which the notice response transaction is based.

Line responses may be given for the container that describes the request to publish a notice or they can be related to the referenced notice within the container.

[source,xml,indent=0]
.Example of line reference
....
include::../files/QualificationRejection.xml[tags=lineReference]
....
<.> Identifies the section of the notice to which the reported issue applies. Please use the XPath of the transaction header if a concrete XPath to the line cannot be given


==== Line response information

Line response information provides details about a given validation error.

[source,xml,indent=0]
.Example of line response
....
include::../files/QualificationRejection.xml[tags=lineResponseResponse]
....
<.> A code stating whether the referenced line was (conditionally) accepted or rejected.
<.> The description of the issue identified in the transaction document, if possible a error message from a schematron or xml should be used to give a more detailed insight
<.> A codified version of the issue description that describes the nature of the issue e.g. Syntax violation, Business rule violation, etc. Refer to the code list status reason code.

