
= PEPPOL Identifiers

PEPPOL has defined a Policy for Using Identifiers that specifies how to use identifiers in both its transport infrastructure and within the documents exchanged across that infrastructure. It also introduces principles for any identifiers used in the PEPPOL environment.

== Profile ID

[IMPORTANT]
All transactions within this profile uses the same profile identifier.

[cols="2*2,2*4", options="header"]
.The table below shows values to be used for the Profile ID
|===

| TransactionID
| Transaction name
| Short Description
| `cbc:ProfileID`

| T001
| Subscribe to Procedure
| EO shows his interest in the procurement project
.4+.^| urn:fdc:peppol.eu:prac:bis:p001:1.2

| T002
| Subscribe to Procedure Confirmation
| CA sends acknowledgement to EO including all documents

| T021
| Unsubscribe from Procedure
| EO wants to unsubscribe from the procurement project

| T022
| Unsubscribe from Procedure Confirmation
| CA sends unsubscription acknowledgement to EO

|===

[NOTE]
For implementers, please note that the process identifiers in the document instance MUST correspond to the http://docs.oasis-open.org/bdxr/bdx-smp/v1.0/cs03/bdx-smp-v1.0-cs03.pdf[SMP] process identifier.
