

= PEPPOL Identifiers

//Documentation about PEPPOL identifiers supported by this BIS can be found at the following page: {link-identifier-policy}[eDelivery guide for eTendering].

PEPPOL has defined a Policy for Using Identifiers that specifies how to use identifiers in both its transport infrastructure and within the documents exchanged across that infrastructure. It also introduces principles for any identifiers used in the PEPPOL environment. The e-Tendering pilot adopts and extends the PEPPOL Policy in the following ways:

== Document Identifiers used in business (UBL) documents

=== Profile ID and Customization ID

The PEPPOL Customization ID identifies the specification of content and rules that apply to the transaction. This BIS has required some minor additions and changes to the CEN BII transaction. Following the CEN BII methodology any extension must be communicated by adding an extension ID onto the Customization ID.

The full syntax is:
[source,xml,indent=0]
----
<transactionId>:(restrictive|extended|partly):<extensionId>[(restrictive|extended|partly):<extensionId>]
----

Which customization identification should be used, is based on which transaction is sent, and the extension identification for BIS documents.

[cols="2,2,4,4", options="header"]
.The table below shows an overview of  the values to be used for the Customization ID per transaction.
|===
| TransactionID | Transaction name | Short Description | ProcessID
| BiiTrdm081 | ExpressionOfInterestRequest  | CEO shows his interest in the procurement project | urn:www.cenbii.eu:profile:bii46:ver3.0
| BiiTrdm082 | ExpressionOfInterestResponse | CA SubscibeInterestConfirmations interest EO and sends acknowledgement to EO including all documents | urn:www.cenbii.eu:profile:bii46:ver3.0
| T001 | ExpressionOfInterestRequest | CEO shows his interest in the procurement project | #**urn:www.peppol.eu:profile:p001:ver1.0**#
| T002 | ExpressionOfInterestResponse | CA SubscibeInterestConfirmations interest EO and sends acknowledgement to EO including all documents | #**urn:www.peppol.eu:profile:p001:ver1.0**#
|===

Note:: For implementers, please note that the process identifiers in the document instance MUST correspond to the http://docs.oasis-open.org/bdxr/bdx-smp/v1.0/cs03/bdx-smp-v1.0-cs03.pdf[SMP] process identifier.
