=	Description of the attachment of documents

Using this transaction, the information of the tendering process and the details of the procurement project are described in unstructured files. The Invitation to Tender reference the unstructured files so it is possible to access them through their URI.

The `cac:AdditionalDocumentReference` class contains references to all the files for the tenderers to prepare their bids. The mandatory `cbc:ID` element contains an identifier of the file, and the `cac:DocumentStatusCode` is used to inform the tenderers about the action that has to be done with the current document.

Find below an example on how to define a provided document reference.

In this example, the contents of the coded elements DocumentTypeCode and DocumentStatusCode have been defined following the coded values of `documentTypeCode` to indicate if a document is provided for reading and information or required for return as part of the bid (e.g. a template that need to be filled).


[source,xml,indent=0]
.Additional document reference

----
include::../{xml-doc-file}[tags=AdditionalDocumentReference2]

----
