
= Transport of encryption certificate via any invitation to tender

== Introduction

The Invitation to tender (ItT) business document is used by the contracting authority to provide a qualified economic operator with the latest updated procurement documents. Sending the invitation to tender to any of the remaining economic operators determines the final step of the procurement procedure. Besides transporting procurement documents it MUST be used to transport the encryption certificate needed by the economic operator to encrypt his tender for submission.
#Since the invitation to tender is also used to sent out business document changes after the tenderer has requested for status-updates (by sending a status-update-inquiry), any Invitation to tender MUST contain the encryption certificate needed by the economic operator to encrypt his tender for submission.
== Encryption certificate

The encryption certificate MUST be transported as an attachment within the invitation to tender's'ASIC. The Invitation to tender business document contains metadata regarding all attachments thus also for the tender encryption certificate.

This metadata is resembled by the UBL container cac:AdditionalDocumentReference. In the case of the encryption certificate this container MUST contain the elements and values mentioned in the table below.

To identify the encryption certificate, the UBL MUST contain exactly one AdditionalDocumentReference-container as described below. Any other container MUST NOT make use of this value combination.

[cols="3,2,3,4", options="header"]
|===
| Business term | Card. | XPath within +
 cac:AdditionalDocumentReference | Value / Description
| Required document reference identifier | 1..1 | cbc:ID | Reference identifier of a document that is provided as part of a tender or call for tenders.
Value supplied by tendering system of the CA. Is not necessarily populated with the filename but rather an internal identifier.
| Document issue date | 0..1 | cbc:IssueDate |The date on which the tender encryption key has been issued.
| Document type code | 1..1 | cbc:DocumentTypeCode | Fixed value of “PROVIDED”
| | | cbc:DocumentTypeCode/@listID | Fixed value of "urn:eu:esens:cenbii:documentType"
| Provided document version | 0..1 | cbc:VersionID | Version of a document that is provided as part of a tender or call for tenders.
| Provided document to be returned indicator | 1..1 | cbc:DocumentStatusCode | Fixed value of “NO RETURN”
| | | cbc:DocumentStatusCode/@listID | Fiexd value of "urn:eu:esens:cenbii:documentStatusType"
| Document mime type code | 1..1 | cac:Attachment/cac:ExternalReference/cbc:MimeCode | Fixed value of "application/pkix-cert".
| Provided document name | 1..1 | cac:Attachment/cac:ExternalReference/cbc:FileName | Name of a document that is provided as part of a tender or call for tenders. The extension of the file MUST be  “cer”.
|===


[source,xml,indent=0]
.Example of the CfT (partly) for transporting the encryption certificate

----
include::../{xml-doc-file}[tags=AdditionalDocumentReference1]

----

//http://wiki.ds.unipi.gr/download/attachments/31425187/20170127%20-%20CfT.xml?version=1&modificationDate=1485523756000&api=v2[20170127 - CfT.xml]
