[[descriptions]]
= Description of selected parts of the transaction

Limited support for this, see {name-profile-org}.

== Process control

=== Specification identification

Identifier for the set of rules and transactions for the Tender Withdrawal Reception Notification.

[source,xml,indent=0]
....
include::../files/TenderWithdrawal.xml[tags=specification-identification]
....
<.> The value for the specification identification is always "_urn:www.cenbii.eu:transaction:biitrdm089:ver3.0:extended:urn:fdc:peppol.eu:2021:pracc:t013:ver1.0_".


=== Business Process Type Identifier

Identifier for the business process context of the Tender Withdrawal Reception Notification.

[source,xml,indent=0]
....
include::../files/TenderWithdrawal.xml[tags=business-process-type-identifier]
....
<.> The value for the business process type identifier is always "_urn:fdc:peppol.eu:2021:pracc:p007:01:1.0_".

== Document References

=== Document identifier

Identifier of the Tender Withdrawal Reception Notification itself.

[source,xml,indent=0]
....
include::../files/TenderWithdrawal.xml[tags=document-identifier]
....
<.> The Document Identifier must be expressed in a UUID syntax (RFC 4122).

=== Reference Number

An identifier that is specified by the buyer and used as a reference number for all documents in the procurement process. It is also known as procurement project identifier, procurement reference number or contract folder identifier.
In UBL the reference number is represented by the ContractFolder ID.

[source,xml,indent=0]
....
include::../files/TenderWithdrawal.xml[tags=reference-number]
....
<.> The Reference Number must be expressed in a UUID syntax (RFC 4122).

=== Tender Document Reference

The tender reception notification contains the reference to the tender document sent by the economic operator. The contracting authority should refer to the tender by using the document hash, and the hash algorithm method used.

==== Tender document reference ID

....
include::../files/TenderWithdrawal.xml[tags=received-document-reference]
....

<.> DocumentReference Identifier for a Call for Tender Reference must be expressed in a UUID syntax (RFC 4122).

==== Document hash algorithm

....
include::../files/TenderWithdrawal.xml[tags=document-digest]
....
<.> In this tag goes the digest of the document.
<.> Document hash algorithm must be "_http://www.w3.org/2001/04/xmlenc#sha256_".

=== Tender Notification Document Reference

Identifier of the tender reception notification message.
....
include::../files/TenderWithdrawal.xml[tags=tender-notification-document-reference]
....
<.> Tender Notification Document Reference for a Call for Tender Reference must be expressed in a UUID syntax (RFC 4122).

== Parties

=== Contracting Body

The contracting authority or contracting entity who is buying supplies, services or public works using a tendering procedure as described in the applicable directive (Directives 2014/24/EU, 2014/25/EU).

[source,xml,indent=0]
.Contracting Body is represented in UBL 2.3 using Contracting Party:

[source,xml,indent=0]
....
include::../files/TenderWithdrawal.xml[tags=contracting-party]
....
<.> At first the EndpointID with its schemeID has to be clarified. The schemeID is an attribute of the EndpointID and has to be chosen according to the EndpointID.
<.> Following the EndpointID the Identification of the Party has to be given in the same manner.
<.> The same value as in the EndpointID also the EndpointID has to be given into the ID and the corresponding attribute for the schemeID.
<.> Additional to the Party Identification the Party Name has to be given. It is put into the Name tag of the PartyName.

=== Economic Operator

Any natural or legal person or public entity or group of such persons and/or entities, including any temporary association of undertakings, which offers the execution of works and/or a work, the supply of products, or the provision of services on the market.

[source,xml,indent=0]
.The Economic Operator is represented in UBL 2.3 using the Tenderer Party:

....
include::../files/TenderWithdrawal.xml[tags=tenderer-party]
....
<.> At first the EndpointID with its schemeID has to be clarified. The schemeID is an attribute of the EndpointID and has to be chosen according to the EndpointID.
<.> Following the EndpointID the Identification of the Party has to be given in the same manner.
<.> Additional to the Party Identification the Party Name has to be given. It is put into the Name tag of the PartyName.
<.> Furthermore, the PostalAdress of the Economic operator can be given.
<.> Address line 1
<.> Address line 2
<.> City
<.> Post Code
<.> Country Subdivision
<.> Country tag for the Country Code
<.> Country Code

=== Tenderer Party Contact

Used to provide contacting information for a party in general or a person. Optional information additional to the Economic Operator.
....
include::../files/TenderWithdrawal.xml[tags=tenderer-party-contact]
....
<.> Introduction to the contact. The contact consists of four additional elements.
<.> Full name of the contact
<.> Telephone number of the contact, as a String
<.> Telefax number of the contact, as a String, if given
<.> E-Mail address of the contact

== Additional Tags

=== Document Date Time
Issue date and time must be sent.

Issue date is a xs:date data type, and the date is specified as "YYYY-MM-DD" where:

* YYYY - four digit year
* MM - two digit month (01 to 12)
* DD - two digit day (0)

Issue time is a xs:time data type, and the time is specified as "hh:mm:ss" where:

* hh - two digits of hour (00 to 23) (am/pm NOT allowed).
* mm - two digits of minute (00 to 59)
* ss - two digits of second (00 to 59)
* TZD - time zone designator (Z or +hh:mm or -hh:mm)

The issue date and time refer to the issuance of the tender receipt notification.

NOTE: The issue time must specify the time zone.

[source,xml,indent=0]
.Example of Issue date/time and Registered date/time

....
include::../files/TenderWithdrawal.xml[tags=document-date-time]
....
<.> Date when the referred document was issued by the sending party.
<.> Time when the referred document was issued by the sending party, granular to seconds and timezone.

=== Withdraw Offer Indicator
Indicates that the economic operator states that he wants to withdraw the offer (true).

....
include::../files/TenderWithdrawal.xml[tags=withdraw-offer-indicator]
....
<.> Boolean, must be true to act according to the message.
