
= PEPPOL Identifiers and Profile ID

PEPPOL has defined a Policy for Using Identifiers that specifies how to use identifiers in both its transport infrastructure and within the documents exchanged across that infrastructure. It also introduces principles for any identifiers used in the PEPPOL environment.

[IMPORTANT]
All transactions within this profile uses the same profile identifier.

[cols="2*2,2*4", options="header"]
.The table below shows values to be used for the Business Process Type Identifier
|===

| TransactionID
| Transaction name
| Short Description
| `cbc:ProfileID`

| T019
| Qualification
| EO sends his qualification documents for the procurement project to CA
.2+.^| urn:fdc:peppol.eu:prac:bis:p011:1.1

| T020
| Qualification Reception Confirmation
| CA sends acknowledgement to EO

|===

[NOTE]
For implementers, please note that the process identifiers in the document instance MUST correspond to the http://docs.oasis-open.org/bdxr/bdx-smp/v1.0/cs03/bdx-smp-v1.0-cs03.pdf[SMP] process identifier.
