[[descriptions]]
= Descriptions of selected parts of the transaction

Limited support for this, see {link-bii3}.

== AdditionalDocumentReferences and Attachments

How to combine questions in a transaction.

=== Question about a procurement procedure

[source,xml,indent=0]
....
include::../files/TenderingQuestions-doc.xml[tags=contract-folder-id;question-contract-folder-id]
....
<1> The Contract Folder ID of the procedure
<2> A reference to an element where one or more questions are located. The number in square brackets is the position in the list of Attachment. The position starts with 1 (1-based indexing).

=== Questions about a group of lots of a procurement procedure

[source,xml,indent=0]
....
include::../files/TenderingQuestions-doc.xml[tags=multiple-questions-group-of-lots;question-group-of-lots]
....
<1> The ID of the group of lots.
<2> A reference to a question.
<3> A reference to an attachment.
<4> Refers to a file within the ASiC-e.

=== A question about several lots in a procurement procedure

[source,xml,indent=0]
....
include::../files/TenderingQuestions-doc.xml[tags=one-question-for-multiple-lots;question-for-multiple-lots]
....
<1> A lot reference.
<2> An other lot reference.
<3> Reference to the same question.
