// TODO adapt to Invitation for Tender
= Implementation guidelines

{name-profile} is based on work done by {link-bii3}, and business rules and code lists used are inherited from the following {link-bii3} and {link-ubl-22} documents:

urn:oasis:names:specification:ubl:schema:xsd:TenderStatusRequest-2
urn:oasis:names:specification:ubl:schema:xsd:InvitationToTender-2

The syntax mapping for {name-profile} has been tested and revised during the {link-esens} pilot and is based on transaction description for Tender Status Inquiry (Trdm097) and  Call for Tenders (Trdm083) done by {link-bii3}. Requirements, business rules and code lists used are inherited from the follwoing documents:

* {link-profile}
* {link-profile2}
* {sig-cft}
* {tender-status}
* {call-for-tenders}

{link-peppol} {name-profile} business process includes 2 transactions:

* link:../../transactions/T024/index.html[T024 Invitation To Tender]
* link:../../transactions/T025/index.html[T025 Invitation To Tender Status Inquiry]

